version: '3.8'

services:
  db: 
    image: postgres
    restart: always
    environment: 
      DATABASE_HOST: localhost
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: sa
      POSTGRES_DB: SalesHubDB
    expose: 
      - "5432"

  api:
    build:
      context: .
      dockerfile: saleshub-api.dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/SalesHubAPI/
    command: flask --app saleshubapi/ run --debug -h 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: reduhq@gmail.com
      PGADMIN_DEFAULT_PASSWORD: reduhq
    ports:
      - "80:80"